import 'package:activityforecast/components/weather_icons.dart';
import 'package:flutter/material.dart';
import 'package:weather_icons/weather_icons.dart';

Map<String, List<IconData>> activityIcons = {
  'physical': physicalIcons,
  'warm weather': warmWeatherIcon,
  'cold weather': coldWeatherIcon,
  'travel': travelIcons,
  'place': placesIcons,
  'all': allIcons
};

Map activityTabIcons = {
  'physical': Icons.directions_run,
  'warm weather': Icons.wb_sunny,
  'cold weather': Icons.snowmobile_sharp,
  'travel': Icons.directions_car,
  'place': Icons.store,
  'all': Icons.menu,
};

List<IconData> physicalIcons = [
  Icons.sports_baseball,
  Icons.sports_basketball,
  Icons.sports_cricket,
  Icons.sports_football,
  Icons.sports_golf,
  Icons.sports_handball,
  Icons.sports_hockey,
  Icons.sports_mma,
  Icons.sports_motorsports,
  Icons.sports_rugby,
  Icons.sports_soccer,
  Icons.sports_tennis,
  Icons.sports_volleyball,
  Icons.fitness_center,
  Icons.directions_run,
  Icons.directions_walk,
  Icons.nordic_walking,
  Icons.downhill_skiing,
  Icons.directions_bike,
  Icons.self_improvement,
  Icons.hiking,
  Icons.paragliding,
  Icons.pool,
  Icons.rowing,
  Icons.sailing,
  Icons.kayaking,
  Icons.surfing,
  Icons.kitesurfing,
  Icons.ice_skating,
  Icons.skateboarding,
  Icons.sledding,
  Icons.snowboarding,
  Icons.snowmobile,
  Icons.snowshoeing,
];

List<IconData> coldWeatherIcon = [
  Icons.ice_skating,
  Icons.downhill_skiing,
  Icons.sports_esports,
  Icons.sledding,
  Icons.snowboarding,
  Icons.snowmobile,
  Icons.snowshoeing,
  Icons.cottage,
  Icons.fireplace,
];

List<IconData> warmWeatherIcon = [
  Icons.self_improvement,
  Icons.directions_run,
  Icons.directions_walk,
  Icons.nordic_walking,
  Icons.directions_bike,
  Icons.kitesurfing,
  Icons.surfing,
  Icons.skateboarding,
  Icons.outdoor_grill,
  Icons.paragliding,
  Icons.park,
  Icons.pool,
  Icons.kayaking,
  Icons.rowing,
  Icons.sailing,
  Icons.beach_access,
  Icons.icecream,
];

List<IconData> travelIcons = [
  Icons.directions_car,
  Icons.electric_car,
  Icons.directions_bus,
  Icons.directions_boat,
  Icons.directions_bike,
  Icons.directions_ferry,
  Icons.directions_railway,
  Icons.directions_subway,
  Icons.electric_bike,
  Icons.motorcycle,
  Icons.pedal_bike,
  Icons.agriculture,
];

List<IconData> placesIcons = [
  Icons.fitness_center,
  Icons.school,
  Icons.store,
  Icons.apartment,
  Icons.beach_access,
  Icons.bungalow,
  Icons.cabin,
  Icons.cottage,
  Icons.casino,
  Icons.icecream,
  Icons.theaters,
  Icons.landscape,
  Icons.local_bar,
  Icons.local_cafe,
  Icons.local_dining,
  Icons.local_fire_department,
  Icons.local_florist,
  Icons.local_gas_station,
  Icons.local_hospital,
  Icons.local_laundry_service,
  Icons.local_library,
  Icons.local_mall,
  Icons.local_movies,
  Icons.local_offer,
  Icons.local_phone,
  Icons.local_pizza,
  Icons.local_see,
  Icons.local_shipping,
  Icons.local_taxi,
  Icons.location_city,
  Icons.lunch_dining,
  Icons.sports_bar,
  Icons.place,
  Icons.terrain,
  Icons.ramen_dining,
];

List<IconData> allIcons = [
  Icons.ac_unit,
  Icons.access_time,
  Icons.accessibility,
  Icons.accessible,
  Icons.account_balance,
  Icons.account_balance_wallet,
  Icons.agriculture,
  Icons.air,
  Icons.airplanemode_active,
  Icons.airplanemode_inactive_outlined,
  Icons.alarm,
  Icons.all_inclusive,
  Icons.alt_route,
  Icons.analytics,
  Icons.anchor,
  Icons.apartment,
  Icons.architecture,
  Icons.arrow_back,
  Icons.arrow_forward,
  Icons.article,
  Icons.assessment,
  Icons.assignment,
  Icons.attach_money,
  Icons.attachment,
  Icons.attractions,
  Icons.audiotrack,
  Icons.backpack,
  Icons.bathroom,
  Icons.bathtub,
  Icons.battery_full,
  Icons.beach_access,
  Icons.bed,
  Icons.bedtime,
  Icons.biotech,
  Icons.blender,
  Icons.bluetooth,
  Icons.bolt,
  Icons.bookmark,
  Icons.brightness_1,
  Icons.brightness_2,
  Icons.brightness_3,
  Icons.brush,
  Icons.bug_report,
  Icons.build,
  Icons.bungalow,
  Icons.bus_alert,
  Icons.business,
  Icons.business_center,
  Icons.cabin,
  Icons.cable,
  Icons.cached,
  Icons.cake,
  Icons.calendar_view_month,
  Icons.call,
  Icons.call_end,
  Icons.camera,
  Icons.camera_alt,
  Icons.camera_front,
  Icons.camera_roll,
  Icons.campaign,
  Icons.carpenter,
  Icons.cases,
  Icons.casino,
  Icons.celebration,
  Icons.chair,
  Icons.child_friendly,
  Icons.clean_hands,
  Icons.cleaning_services,
  Icons.clear,
  Icons.cloud,
  Icons.coffee,
  Icons.color_lens,
  Icons.comment,
  Icons.computer,
  Icons.construction,
  Icons.content_cut,
  Icons.coronavirus,
  Icons.cottage,
  Icons.create,
  Icons.credit_card,
  Icons.cut,
  Icons.dangerous,
  Icons.dark_mode,
  Icons.delete,
  Icons.device_thermostat,
  Icons.devices,
  Icons.dining_rounded,
  Icons.directions_bike,
  Icons.directions_boat,
  Icons.directions_bus,
  Icons.directions_car,
  Icons.directions_ferry,
  Icons.directions_railway,
  Icons.directions_run,
  Icons.directions_subway,
  Icons.directions_walk,
  Icons.do_not_disturb,
  Icons.done,
  Icons.doorbell,
  Icons.downhill_skiing,
  Icons.dry_cleaning,
  Icons.eco,
  Icons.edit,
  Icons.elderly,
  Icons.electric_bike,
  Icons.electric_car,
  Icons.emoji_emotions,
  Icons.emoji_events,
  Icons.emoji_food_beverage,
  Icons.emoji_nature,
  Icons.emoji_people,
  Icons.engineering,
  Icons.explore,
  Icons.extension,
  Icons.fastfood,
  Icons.favorite,
  Icons.feedback,
  Icons.festival,
  Icons.fingerprint,
  Icons.fireplace,
  Icons.fitness_center,
  Icons.flag,
  Icons.flash_on,
  Icons.flashlight_on,
  Icons.flight,
  Icons.folder,
  Icons.food_bank,
  Icons.foundation,
  Icons.free_breakfast,
  Icons.games,
  Icons.grade,
  Icons.grass,
  Icons.hardware,
  Icons.headphones,
  Icons.hiking,
  Icons.home,
  Icons.hot_tub,
  Icons.hourglass_bottom,
  Icons.https,
  Icons.ice_skating,
  Icons.icecream,
  Icons.inventory,
  Icons.kayaking,
  Icons.keyboard,
  Icons.kitesurfing,
  Icons.landscape,
  Icons.language,
  Icons.laptop,
  Icons.local_bar,
  Icons.local_cafe,
  Icons.local_dining,
  Icons.local_fire_department,
  Icons.local_florist,
  Icons.local_gas_station,
  Icons.local_hospital,
  Icons.local_laundry_service,
  Icons.local_library,
  Icons.local_mall,
  Icons.local_movies,
  Icons.local_offer,
  Icons.local_phone,
  Icons.local_pizza,
  Icons.local_see,
  Icons.local_shipping,
  Icons.local_taxi,
  Icons.location_city,
  Icons.lock,
  Icons.luggage,
  Icons.lunch_dining,
  Icons.map,
  Icons.masks,
  Icons.medical_services_rounded,
  Icons.mic,
  Icons.mic_off,
  Icons.microwave,
  Icons.miscellaneous_services,
  Icons.mode_edit,
  Icons.monetization_on,
  Icons.mood,
  Icons.mood_bad,
  Icons.motorcycle,
  Icons.mouse,
  Icons.movie_creation,
  Icons.music_note,
  Icons.nordic_walking,
  Icons.not_interested,
  Icons.notifications,
  Icons.opacity,
  Icons.outdoor_grill,
  Icons.paragliding,
  Icons.park,
  Icons.pedal_bike,
  Icons.people,
  Icons.person,
  Icons.pest_control,
  Icons.pets,
  Icons.phone_iphone,
  Icons.piano,
  Icons.pin_drop,
  Icons.place,
  Icons.plumbing,
  Icons.podcasts,
  Icons.pool,
  Icons.priority_high,
  Icons.public,
  Icons.push_pin,
  Icons.radio,
  Icons.ramen_dining,
  Icons.rowing,
  Icons.sailing,
  Icons.savings,
  Icons.school,
  Icons.search,
  Icons.self_improvement,
  Icons.sentiment_dissatisfied,
  Icons.sentiment_dissatisfied_outlined,
  Icons.sentiment_neutral,
  Icons.sentiment_satisfied,
  Icons.sentiment_satisfied_alt,
  Icons.sentiment_very_dissatisfied,
  Icons.sentiment_very_dissatisfied_outlined,
  Icons.sentiment_very_satisfied,
  Icons.sentiment_very_satisfied_outlined,
  Icons.settings,
  Icons.settings_accessibility,
  Icons.settings_voice,
  Icons.shopping_bag,
  Icons.shopping_cart,
  Icons.shower,
  Icons.sick,
  Icons.skateboarding,
  Icons.sledding,
  Icons.snowboarding,
  Icons.snowmobile,
  Icons.snowshoeing,
  Icons.soap,
  Icons.speaker,
  Icons.speed,
  Icons.sports_bar,
  Icons.sports_baseball,
  Icons.sports_basketball,
  Icons.sports_cricket,
  Icons.sports_esports,
  Icons.sports_football,
  Icons.sports_golf,
  Icons.sports_handball,
  Icons.sports_hockey,
  Icons.sports_mma,
  Icons.sports_motorsports,
  Icons.sports_rugby,
  Icons.sports_score,
  Icons.sports_sharp,
  Icons.sports_soccer,
  Icons.sports_tennis,
  Icons.sports_volleyball,
  Icons.store,
  Icons.surfing,
  Icons.terrain,
  Icons.theaters,
  Icons.umbrella,
  Icons.video_camera_back,
  Icons.wc,
];

// const List originalIcon = [
//   Icons.ac_unit,
//   Icons.access_time,
//   Icons.accessibility,
//   Icons.accessible,
//   Icons.account_balance,
//   Icons.account_balance_wallet,
//   // Icons.agriculture,
//   Icons.air,
//   Icons.airplanemode_active,
//   Icons.airplanemode_inactive_outlined,
//   Icons.alarm,
//   Icons.all_inclusive,
//   Icons.alt_route,
//   Icons.analytics,
//   Icons.anchor,
//   // Icons.apartment,
//   Icons.architecture,
//   Icons.arrow_back,
//   Icons.arrow_forward,
//   Icons.article,
//   Icons.assessment,
//   Icons.assignment,
//   Icons.attach_money,
//   Icons.attachment,
//   Icons.attractions,
//   Icons.audiotrack,
//   Icons.backpack,
//   Icons.bathroom,
//   Icons.bathtub,
//   Icons.battery_full,
//   // Icons.beach_access,
//   Icons.bed,
//   Icons.bedtime,
//   Icons.biotech,
//   Icons.blender,
//   Icons.bluetooth,
//   Icons.bolt,
//   Icons.bookmark,
//   Icons.brightness_1,
//   Icons.brightness_2,
//   Icons.brightness_3,
//   Icons.brush,
//   Icons.bug_report,
//   Icons.build,
//   // Icons.bungalow,
//   Icons.bus_alert,
//   Icons.business,
//   Icons.business_center,
//   // Icons.cabin,
//   Icons.cable,
//   Icons.cached,
//   Icons.cake,
//   Icons.calendar_view_month,
//   Icons.call,
//   Icons.call_end,
//   Icons.camera,
//   Icons.camera_alt,
//   Icons.camera_front,
//   Icons.camera_roll,
//   Icons.campaign,
//   Icons.carpenter,
//   Icons.cases,
//   // Icons.casino,
//   Icons.celebration,
//   Icons.chair,
//   Icons.child_friendly,
//   Icons.clean_hands,
//   Icons.cleaning_services,
//   Icons.clear,
//   Icons.cloud,
//   Icons.coffee,
//   Icons.color_lens,
//   Icons.comment,
//   Icons.computer,
//   Icons.construction,
//   Icons.content_cut,
//   Icons.coronavirus,
//   // Icons.cottage,
//   Icons.create,
//   Icons.credit_card,
//   Icons.cut,
//   Icons.dangerous,
//   Icons.dark_mode,
//   Icons.delete,
//   Icons.device_thermostat,
//   Icons.devices,
//   Icons.dining_rounded,
//   // Icons.directions_bike,
//   // Icons.directions_boat,
//   // Icons.directions_bus,
//   // Icons.directions_car,
//   // Icons.directions_ferry,
//   // Icons.directions_railway,
//   // Icons.directions_run,
//   // Icons.directions_subway,
//   // Icons.directions_walk,
//   Icons.do_not_disturb,
//   Icons.done,
//   Icons.doorbell,
//   // Icons.downhill_skiing,
//   Icons.dry_cleaning,
//   Icons.eco,
//   Icons.edit,
//   Icons.elderly,
//   // Icons.electric_bike,
//   // Icons.electric_car,
//   Icons.emoji_emotions,
//   Icons.emoji_events,
//   Icons.emoji_food_beverage,
//   Icons.emoji_nature,
//   Icons.emoji_people,
//   Icons.engineering,
//   Icons.explore,
//   Icons.extension,
//   Icons.fastfood,
//   Icons.favorite,
//   Icons.feedback,
//   Icons.festival,
//   Icons.fingerprint,
//   // Icons.fireplace,
//   // Icons.fitness_center,
//   Icons.flag,
//   Icons.flash_on,
//   Icons.flashlight_on,
//   Icons.flight,
//   Icons.folder,
//   Icons.food_bank,
//   Icons.foundation,
//   Icons.free_breakfast,
//   Icons.games,
//   Icons.grade,
//   Icons.grass,
//   Icons.hardware,
//   Icons.headphones,
//   // Icons.hiking,
//   Icons.home,
//   Icons.hot_tub,
//   Icons.hourglass_bottom,
//   Icons.https,
//   // Icons.ice_skating,
//   Icons.icecream,
//   Icons.inventory,
//   // Icons.kayaking,
//   Icons.keyboard,
//   // Icons.kitesurfing,
//   Icons.landscape,
//   Icons.language,
//   Icons.laptop,
//   // Icons.local_bar,
//   // Icons.local_cafe,
//   // Icons.local_dining,
//   // Icons.local_fire_department,
//   // Icons.local_florist,
//   // Icons.local_gas_station,
//   // Icons.local_hospital,
//   // Icons.local_laundry_service,
//   // Icons.local_library,
//   // Icons.local_mall,
//   // Icons.local_movies,
//   // Icons.local_offer,
//   // Icons.local_phone,
//   // Icons.local_pizza,
//   // Icons.local_see,
//   // Icons.local_shipping,
//   // Icons.local_taxi,
//   // Icons.location_city,
//   Icons.lock,
//   Icons.luggage,
//   // Icons.lunch_dining,
//   Icons.map,
//   Icons.masks,
//   Icons.medical_services_rounded,
//   Icons.mic,
//   Icons.mic_off,
//   Icons.microwave,
//   Icons.miscellaneous_services,
//   Icons.mode_edit,
//   Icons.monetization_on,
//   Icons.mood,
//   Icons.mood_bad,
//   // Icons.motorcycle,
//   Icons.mouse,
//   Icons.movie_creation,
//   Icons.music_note,
//   // Icons.nordic_walking,
//   Icons.not_interested,
//   Icons.notifications,
//   Icons.opacity,
//   // Icons.outdoor_grill,
//   // Icons.paragliding,
//   // Icons.park,
//   // Icons.pedal_bike,
//   Icons.people,
//   Icons.person,
//   Icons.pest_control,
//   Icons.pets,
//   Icons.phone_iphone,
//   Icons.piano,
//   Icons.pin_drop,
//   // Icons.place,
//   Icons.plumbing,
//   Icons.podcasts,
//   Icons.pool,
//   Icons.priority_high,
//   Icons.public,
//   Icons.push_pin,
//   Icons.radio,
//   // Icons.ramen_dining,
//   // Icons.rowing,
//   // Icons.sailing,
//   Icons.savings,
//   // Icons.school,
//   Icons.search,
//   // Icons.self_improvement,
//   Icons.sentiment_dissatisfied,
//   Icons.sentiment_dissatisfied_outlined,
//   Icons.sentiment_neutral,
//   Icons.sentiment_satisfied,
//   Icons.sentiment_satisfied_alt,
//   Icons.sentiment_very_dissatisfied,
//   Icons.sentiment_very_dissatisfied_outlined,
//   Icons.sentiment_very_satisfied,
//   Icons.sentiment_very_satisfied_outlined,
//   Icons.settings,
//   Icons.settings_accessibility,
//   Icons.settings_voice,
//   Icons.shopping_bag,
//   Icons.shopping_cart,
//   Icons.shower,
//   Icons.sick,
//   // Icons.skateboarding,
//   // Icons.sledding,
//   // Icons.snowboarding,
//   // Icons.snowmobile,
//   // Icons.snowshoeing,
//   Icons.soap,
//   Icons.speaker,
//   Icons.speed,
//   // Icons.sports_bar,
//   // Icons.sports_baseball,
//   // Icons.sports_basketball,
//   // Icons.sports_cricket,
//   // Icons.sports_esports,
//   // Icons.sports_football,
//   // Icons.sports_golf,
//   // Icons.sports_handball,
//   // Icons.sports_hockey,
//   // Icons.sports_mma,
//   // Icons.sports_motorsports,
//   // Icons.sports_rugby,
//   Icons.sports_score,
//   Icons.sports_sharp,
//   // Icons.sports_soccer,
//   // Icons.sports_tennis,
//   // Icons.sports_volleyball,
//   // Icons.store,

//   // Icons.surfing,
//   // Icons.terrain,
//   // Icons.theaters,
//   Icons.umbrella,
//   Icons.video_camera_back,
//   Icons.wc,
// ];
